# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean install'
    #sonarQubeRunAnalysis: true
    #checkStyleRunAnalysis: true
    #pmdRunAnalysis: true
    #codeCoverageSourceDirectories: 
- script: mvn clean install verify # Command to run tests    
- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/surefire-reports/TEST-*.xml,**/target/cucumber-reports/cucumber.xml'
    testRunTitle: 'JUnit and Cucumber Tests'
    searchFolder: '$(System.DefaultWorkingDirectory)'
    failTaskOnFailedTests: true